import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#4F46E5',
    primaryContainer: '#E0E7FF',
    secondary: '#06B6D4',
    secondaryContainer: '#CFFAFE',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    surfaceVariant: '#F1F5F9',
    error: '#EF4444',
    errorContainer: '#FEE2E2',
    onSurface: '#1E293B',
    onSurfaceVariant: '#64748B',
    outline: '#E2E8F0',
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
    inverseSurface: '#1E293B',
    inverseOnSurface: '#F8F9FA',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#FFFFFF',
      level3: '#FFFFFF',
      level4: '#FFFFFF',
      level5: '#FFFFFF',
    },
  },
  roundness: 16,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#818CF8',
    primaryContainer: '#312E81',
    secondary: '#22D3EE',
    secondaryContainer: '#164E63',
    background: '#0F172A',
    surface: '#1E293B',
    surfaceVariant: '#334155',
    error: '#F87171',
    errorContainer: '#7F1D1D',
    onSurface: '#F1F5F9',
    onSurfaceVariant: '#94A3B8',
    outline: '#334155',
    success: '#34D399',
    warning: '#FBBF24',
    info: '#60A5FA',
    inverseSurface: '#F1F5F9',
    inverseOnSurface: '#0F172A',
    elevation: {
      level0: 'transparent',
      level1: '#1E293B',
      level2: '#1E293B',
      level3: '#1E293B',
      level4: '#1E293B',
      level5: '#1E293B',
    },
  },
  roundness: 16,
};
