import { Product, Category } from '#/models';

const CATEGORY_ICONS: Record<string, string> = {
  '手机数码': 'cellphone',
  '电脑办公': 'laptop',
  '家用电器': 'television',
  '服饰鞋包': 'tshirt-crew',
  '食品生鲜': 'food-apple',
  '美妆护肤': 'lipstick',
  '家居家装': 'sofa',
  '运动户外': 'basketball',
};

export const categories: Category[] = [
  {
    id: 1,
    name: '手机数码',
    icon: CATEGORY_ICONS['手机数码'],
    children: [
      { id: 101, name: '手机', icon: 'cellphone', parentId: 1 },
      { id: 102, name: '耳机', icon: 'headphones', parentId: 1 },
      { id: 103, name: '平板', icon: 'tablet', parentId: 1 },
      { id: 104, name: '智能手表', icon: 'watch', parentId: 1 },
    ],
  },
  {
    id: 2,
    name: '电脑办公',
    icon: CATEGORY_ICONS['电脑办公'],
    children: [
      { id: 201, name: '笔记本', icon: 'laptop', parentId: 2 },
      { id: 202, name: '键盘', icon: 'keyboard', parentId: 2 },
      { id: 203, name: '鼠标', icon: 'mouse', parentId: 2 },
      { id: 204, name: '显示器', icon: 'monitor', parentId: 2 },
    ],
  },
  {
    id: 3,
    name: '家用电器',
    icon: CATEGORY_ICONS['家用电器'],
    children: [
      { id: 301, name: '电视', icon: 'television', parentId: 3 },
      { id: 302, name: '空调', icon: 'air-conditioner', parentId: 3 },
      { id: 303, name: '冰箱', icon: 'fridge', parentId: 3 },
      { id: 304, name: '洗衣机', icon: 'washing-machine', parentId: 3 },
    ],
  },
  {
    id: 4,
    name: '服饰鞋包',
    icon: CATEGORY_ICONS['服饰鞋包'],
    children: [
      { id: 401, name: '男装', icon: 'tshirt-crew', parentId: 4 },
      { id: 402, name: '女装', icon: 'dress', parentId: 4 },
      { id: 403, name: '运动鞋', icon: 'shoe-sneaker', parentId: 4 },
      { id: 404, name: '箱包', icon: 'briefcase', parentId: 4 },
    ],
  },
  {
    id: 5,
    name: '食品生鲜',
    icon: CATEGORY_ICONS['食品生鲜'],
    children: [
      { id: 501, name: '零食', icon: 'cookie', parentId: 5 },
      { id: 502, name: '水果', icon: 'food-apple', parentId: 5 },
      { id: 503, name: '饮料', icon: 'glass-cocktail', parentId: 5 },
      { id: 504, name: '粮油', icon: 'barley', parentId: 5 },
    ],
  },
  {
    id: 6,
    name: '美妆护肤',
    icon: CATEGORY_ICONS['美妆护肤'],
    children: [
      { id: 601, name: '面部护理', icon: 'face-woman', parentId: 6 },
      { id: 602, name: '彩妆', icon: 'lipstick', parentId: 6 },
      { id: 603, name: '香水', icon: 'bottle-wine', parentId: 6 },
    ],
  },
  {
    id: 7,
    name: '家居家装',
    icon: CATEGORY_ICONS['家居家装'],
    children: [
      { id: 701, name: '家具', icon: 'sofa', parentId: 7 },
      { id: 702, name: '灯具', icon: 'lamp', parentId: 7 },
      { id: 703, name: '收纳', icon: 'archive', parentId: 7 },
    ],
  },
  {
    id: 8,
    name: '运动户外',
    icon: CATEGORY_ICONS['运动户外'],
    children: [
      { id: 801, name: '健身器材', icon: 'dumbbell', parentId: 8 },
      { id: 802, name: '户外装备', icon: 'tent', parentId: 8 },
      { id: 803, name: '球类', icon: 'basketball', parentId: 8 },
    ],
  },
];

function generateProductImage(id: number): string {
  return `https://picsum.photos/seed/product${id}/400/400`;
}

function generateProductImages(id: number): string[] {
  return [
    `https://picsum.photos/seed/product${id}a/400/400`,
    `https://picsum.photos/seed/product${id}b/400/400`,
    `https://picsum.photos/seed/product${id}c/400/400`,
  ];
}

export const products: Product[] = [
  // 手机数码
  {
    id: 1,
    name: 'ProMax 智能手机',
    description: '旗舰级处理器，超清夜景拍摄，5000mAh大电池',
    price: 4999,
    originalPrice: 5999,
    image: generateProductImage(1),
    images: generateProductImages(1),
    categoryId: 101,
    rating: 4.8,
    sales: 12580,
    tags: ['爆款', '包邮'],
    isFlashSale: true,
    flashSalePrice: 4599,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 5).toISOString(),
  },
  {
    id: 2,
    name: '无线降噪耳机 Pro',
    description: '主动降噪，40小时续航，Hi-Res音质认证',
    price: 899,
    originalPrice: 1299,
    image: generateProductImage(2),
    images: generateProductImages(2),
    categoryId: 102,
    rating: 4.7,
    sales: 8560,
    tags: ['热销'],
    isFlashSale: true,
    flashSalePrice: 699,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 3).toISOString(),
  },
  {
    id: 3,
    name: '超薄平板电脑 Air',
    description: '12.9英寸视网膜屏，M2芯片，支持手写笔',
    price: 3999,
    image: generateProductImage(3),
    images: generateProductImages(3),
    categoryId: 103,
    rating: 4.9,
    sales: 4230,
    tags: ['新品'],
  },
  {
    id: 4,
    name: '智能运动手表',
    description: '血氧监测，GPS定位，50米防水',
    price: 1299,
    originalPrice: 1599,
    image: generateProductImage(4),
    images: generateProductImages(4),
    categoryId: 104,
    rating: 4.6,
    sales: 6780,
    tags: ['热卖'],
    isFlashSale: true,
    flashSalePrice: 999,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 8).toISOString(),
  },
  // 电脑办公
  {
    id: 5,
    name: '超极本笔记本',
    description: '14英寸2.8K屏，i7处理器，1TB固态硬盘',
    price: 6999,
    originalPrice: 7999,
    image: generateProductImage(5),
    images: generateProductImages(5),
    categoryId: 201,
    rating: 4.8,
    sales: 3210,
    tags: ['特惠'],
  },
  {
    id: 6,
    name: '机械键盘 RGB',
    description: '青轴手感，全键无冲，自定义RGB灯效',
    price: 399,
    originalPrice: 599,
    image: generateProductImage(6),
    images: generateProductImages(6),
    categoryId: 202,
    rating: 4.5,
    sales: 9870,
    tags: ['爆款'],
    isFlashSale: true,
    flashSalePrice: 299,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 2).toISOString(),
  },
  {
    id: 7,
    name: '无线游戏鼠标',
    description: '16000DPI，低延迟无线，轻量化设计',
    price: 299,
    image: generateProductImage(7),
    images: generateProductImages(7),
    categoryId: 203,
    rating: 4.6,
    sales: 15420,
    tags: ['包邮'],
  },
  {
    id: 8,
    name: '4K专业显示器',
    description: '27英寸4K IPS，HDR400，Type-C一线通',
    price: 2499,
    originalPrice: 2999,
    image: generateProductImage(8),
    images: generateProductImages(8),
    categoryId: 204,
    rating: 4.7,
    sales: 2150,
    tags: ['新品'],
  },
  // 家用电器
  {
    id: 9,
    name: '55英寸智能电视',
    description: '4K超高清，AI语音控制，海量影视资源',
    price: 2299,
    originalPrice: 2999,
    image: generateProductImage(9),
    images: generateProductImages(9),
    categoryId: 301,
    rating: 4.6,
    sales: 5670,
    tags: ['爆款'],
    isFlashSale: true,
    flashSalePrice: 1999,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 6).toISOString(),
  },
  {
    id: 10,
    name: '变频节能空调',
    description: '一级能效，快速冷暖，自清洁功能',
    price: 2699,
    image: generateProductImage(10),
    images: generateProductImages(10),
    categoryId: 302,
    rating: 4.5,
    sales: 4320,
    tags: ['节能'],
  },
  {
    id: 11,
    name: '三门风冷冰箱',
    description: '无霜保鲜，智能温控，大容量存储',
    price: 3299,
    originalPrice: 3999,
    image: generateProductImage(11),
    images: generateProductImages(11),
    categoryId: 303,
    rating: 4.7,
    sales: 2890,
    tags: ['热卖'],
  },
  {
    id: 12,
    name: '滚筒洗衣机',
    description: '10公斤大容量，除菌洗，静音运行',
    price: 1999,
    originalPrice: 2499,
    image: generateProductImage(12),
    images: generateProductImages(12),
    categoryId: 304,
    rating: 4.6,
    sales: 3650,
    tags: ['特惠'],
  },
  // 服饰鞋包
  {
    id: 13,
    name: '纯棉休闲T恤',
    description: '100%纯棉，透气舒适，多色可选',
    price: 79,
    originalPrice: 129,
    image: generateProductImage(13),
    images: generateProductImages(13),
    categoryId: 401,
    rating: 4.4,
    sales: 25680,
    tags: ['爆款', '包邮'],
    isFlashSale: true,
    flashSalePrice: 59,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 4).toISOString(),
  },
  {
    id: 14,
    name: '碎花连衣裙',
    description: '雪纺面料，修身显瘦，夏日必备',
    price: 199,
    originalPrice: 299,
    image: generateProductImage(14),
    images: generateProductImages(14),
    categoryId: 402,
    rating: 4.5,
    sales: 12450,
    tags: ['热销'],
  },
  {
    id: 15,
    name: '轻弹运动鞋',
    description: '缓震科技，透气网面，时尚百搭',
    price: 399,
    image: generateProductImage(15),
    images: generateProductImages(15),
    categoryId: 403,
    rating: 4.7,
    sales: 18760,
    tags: ['新品'],
  },
  {
    id: 16,
    name: '商务双肩包',
    description: '防泼水面料，多层收纳，电脑隔层',
    price: 259,
    originalPrice: 359,
    image: generateProductImage(16),
    images: generateProductImages(16),
    categoryId: 404,
    rating: 4.6,
    sales: 9230,
    tags: ['实用'],
  },
  // 食品生鲜
  {
    id: 17,
    name: '进口坚果大礼包',
    description: '混合坚果，独立包装，营养健康',
    price: 128,
    originalPrice: 168,
    image: generateProductImage(17),
    images: generateProductImages(17),
    categoryId: 501,
    rating: 4.8,
    sales: 32100,
    tags: ['爆款', '包邮'],
    isFlashSale: true,
    flashSalePrice: 99,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 7).toISOString(),
  },
  {
    id: 18,
    name: '新鲜当季水果礼盒',
    description: '精选时令水果，产地直发，新鲜到家',
    price: 168,
    image: generateProductImage(18),
    images: generateProductImages(18),
    categoryId: 502,
    rating: 4.7,
    sales: 15670,
    tags: ['新鲜'],
  },
  {
    id: 19,
    name: '无糖乌龙茶饮料',
    description: '0糖0卡，原叶萃取，清爽解腻',
    price: 39,
    originalPrice: 59,
    image: generateProductImage(19),
    images: generateProductImages(19),
    categoryId: 503,
    rating: 4.5,
    sales: 28900,
    tags: ['热销'],
    isFlashSale: true,
    flashSalePrice: 29,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 1).toISOString(),
  },
  {
    id: 20,
    name: '东北五常大米',
    description: '稻花香2号，颗粒饱满，香软可口',
    price: 89,
    image: generateProductImage(20),
    images: generateProductImages(20),
    categoryId: 504,
    rating: 4.8,
    sales: 45600,
    tags: ['包邮'],
  },
  // 手机数码补充
  {
    id: 21,
    name: '快充移动电源',
    description: '20000mAh大容量，65W双向快充，航空级安全',
    price: 159,
    originalPrice: 229,
    image: generateProductImage(21),
    images: generateProductImages(21),
    categoryId: 101,
    rating: 4.7,
    sales: 34200,
    tags: ['热销', '包邮'],
  },
  {
    id: 22,
    name: '真无线蓝牙耳机',
    description: '蓝牙5.3，低延迟游戏模式，30小时综合续航',
    price: 199,
    originalPrice: 299,
    image: generateProductImage(22),
    images: generateProductImages(22),
    categoryId: 102,
    rating: 4.5,
    sales: 21800,
    tags: ['新品'],
    isFlashSale: true,
    flashSalePrice: 149,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 4).toISOString(),
  },
  // 美妆护肤
  {
    id: 23,
    name: '玻尿酸补水面膜',
    description: '深层补水，舒缓修护，敏感肌可用',
    price: 89,
    originalPrice: 129,
    image: generateProductImage(23),
    images: generateProductImages(23),
    categoryId: 601,
    rating: 4.8,
    sales: 56700,
    tags: ['爆款', '包邮'],
  },
  {
    id: 24,
    name: '氨基酸温和洁面乳',
    description: '温和清洁不紧绷，泡沫绵密，适合日常洁面',
    price: 59,
    image: generateProductImage(24),
    images: generateProductImages(24),
    categoryId: 601,
    rating: 4.6,
    sales: 38900,
    tags: ['热销'],
  },
  {
    id: 25,
    name: '丝绒哑光口红',
    description: '显色度高，持久不脱妆，多色可选',
    price: 129,
    originalPrice: 199,
    image: generateProductImage(25),
    images: generateProductImages(25),
    categoryId: 602,
    rating: 4.7,
    sales: 42300,
    tags: ['热卖'],
    isFlashSale: true,
    flashSalePrice: 99,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 6).toISOString(),
  },
  {
    id: 26,
    name: '清透粉底液',
    description: '轻薄遮瑕，控油持妆，自然裸妆感',
    price: 199,
    image: generateProductImage(26),
    images: generateProductImages(26),
    categoryId: 602,
    rating: 4.5,
    sales: 18700,
    tags: ['新品'],
  },
  {
    id: 27,
    name: '淡香水礼盒',
    description: '清新花果香调，持久留香，精致礼盒装',
    price: 299,
    originalPrice: 399,
    image: generateProductImage(27),
    images: generateProductImages(27),
    categoryId: 603,
    rating: 4.8,
    sales: 12500,
    tags: ['礼盒'],
  },
  {
    id: 28,
    name: '男士古龙水',
    description: '木质香调，沉稳绅士，职场必备',
    price: 259,
    image: generateProductImage(28),
    images: generateProductImages(28),
    categoryId: 603,
    rating: 4.6,
    sales: 9800,
    tags: ['热销'],
  },
  // 家居家装
  {
    id: 29,
    name: '北欧风布艺沙发',
    description: '可拆洗设计，高弹海绵，简约百搭',
    price: 1899,
    originalPrice: 2499,
    image: generateProductImage(29),
    images: generateProductImages(29),
    categoryId: 701,
    rating: 4.7,
    sales: 5600,
    tags: ['特惠'],
  },
  {
    id: 30,
    name: '实木书桌',
    description: '进口橡木，环保漆面，大容量抽屉',
    price: 899,
    image: generateProductImage(30),
    images: generateProductImages(30),
    categoryId: 701,
    rating: 4.5,
    sales: 7200,
    tags: ['包邮'],
  },
  {
    id: 31,
    name: '智能护眼台灯',
    description: '国AA级照度，无蓝光危害，多档调光调色',
    price: 199,
    originalPrice: 299,
    image: generateProductImage(31),
    images: generateProductImages(31),
    categoryId: 702,
    rating: 4.8,
    sales: 28900,
    tags: ['爆款'],
    isFlashSale: true,
    flashSalePrice: 149,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 3).toISOString(),
  },
  {
    id: 32,
    name: '简约落地灯',
    description: '金属灯身，柔和光线，客厅卧室皆宜',
    price: 259,
    image: generateProductImage(32),
    images: generateProductImages(32),
    categoryId: 702,
    rating: 4.6,
    sales: 13400,
    tags: ['新品'],
  },
  {
    id: 33,
    name: '抽屉式收纳柜',
    description: '多层抽屉，透明可视，衣物杂物整理',
    price: 129,
    originalPrice: 169,
    image: generateProductImage(33),
    images: generateProductImages(33),
    categoryId: 703,
    rating: 4.5,
    sales: 45600,
    tags: ['热销'],
  },
  {
    id: 34,
    name: '真空压缩收纳袋',
    description: '节省75%空间，防水防潮，换季收纳神器',
    price: 39,
    image: generateProductImage(34),
    images: generateProductImages(34),
    categoryId: 703,
    rating: 4.7,
    sales: 67800,
    tags: ['实用', '包邮'],
  },
  // 运动户外
  {
    id: 35,
    name: '家用跑步机',
    description: '可折叠设计，静音电机，智能APP互联',
    price: 1999,
    originalPrice: 2999,
    image: generateProductImage(35),
    images: generateProductImages(35),
    categoryId: 801,
    rating: 4.6,
    sales: 3200,
    tags: ['特惠'],
  },
  {
    id: 36,
    name: '瑜伽垫套装',
    description: 'TPE环保材质，防滑纹理，含瑜伽砖拉力带',
    price: 89,
    originalPrice: 129,
    image: generateProductImage(36),
    images: generateProductImages(36),
    categoryId: 801,
    rating: 4.8,
    sales: 53400,
    tags: ['爆款', '包邮'],
    isFlashSale: true,
    flashSalePrice: 69,
    flashSaleEndTime: new Date(Date.now() + 3600000 * 5).toISOString(),
  },
  {
    id: 37,
    name: '双层户外帐篷',
    description: '防雨防风，速开设计，3-4人家庭露营',
    price: 399,
    originalPrice: 599,
    image: generateProductImage(37),
    images: generateProductImages(37),
    categoryId: 802,
    rating: 4.7,
    sales: 8900,
    tags: ['热销'],
  },
  {
    id: 38,
    name: '便携折叠桌椅套装',
    description: '铝合金框架，轻量便携，户外野餐烧烤',
    price: 259,
    image: generateProductImage(38),
    images: generateProductImages(38),
    categoryId: 802,
    rating: 4.5,
    sales: 15600,
    tags: ['实用'],
  },
  {
    id: 39,
    name: '专业篮球',
    description: 'PU吸湿皮革，标准7号球，室内外通用',
    price: 129,
    originalPrice: 169,
    image: generateProductImage(39),
    images: generateProductImages(39),
    categoryId: 803,
    rating: 4.7,
    sales: 21300,
    tags: ['热卖'],
  },
  {
    id: 40,
    name: '羽毛球拍对拍套装',
    description: '全碳素超轻，高弹力线，含羽毛球拍包',
    price: 199,
    image: generateProductImage(40),
    images: generateProductImages(40),
    categoryId: 803,
    rating: 4.6,
    sales: 18700,
    tags: ['包邮'],
  },
];

export const banners = [
  { id: 1, image: 'https://picsum.photos/seed/banner1/800/300', link: 'product/1' },
  { id: 2, image: 'https://picsum.photos/seed/banner2/800/300', link: 'product/2' },
  { id: 3, image: 'https://picsum.photos/seed/banner3/800/300', link: 'product/5' },
  { id: 4, image: 'https://picsum.photos/seed/banner4/800/300', link: 'product/9' },
];

export const hotSearchKeywords = [
  '手机', '耳机', '笔记本', '零食', '运动鞋', 'T恤', '手表', '键盘',
];
